config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/new', to: 'games#new'
  post '/score', to: 'games#score'
  post '/reset', to: 'games#reset'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
require 'open-uri'
require 'json'

class GamesController < ApplicationController
  def new
    # @letters = []
    # alphabet = [*'A'..'Z']
    # 10.times { @letters << alphabet[rand(0..25)] }
    @letters = ('A'..'Z').to_a.sample(10)
    @start = Time.now
  end

  def score
    @word = params[:word]
    @letters = params[:letters]
    @start = Time.parse(params[:start])
    @end = Time.now
    @time_taken = @end - @start
    @english_word = english_word?
    @valid_word = valid_word?
    if @english_word && @valid_word
      @score = @word.length + (10 / @time_taken).round
    else
      @score = 0
    end

    @message = message(@english_word, @valid_word)

    if session[:score]
      session[:score] += @score
    else
      session[:score] = @score
    end
  end

  def reset
    session[:score] = 0
    redirect_to new_path
  end

  private

  def english_word?
    url = "https://wagon-dictionary.herokuapp.com/#{@word}"
    response = JSON.parse(open(url).read)
    response['found']
  end

  def valid_word?
    word_chars = @word.upcase.chars
    letter_chars = @letters.chars
    word_chars.all? do |char|
      word_chars.count(char) <= letter_chars.count(char)
    end
  end

  def message(english_word, valid_word)
    if english_word && valid_word
      'Great Job!!'
    elsif english_word
      'Sorry, this isn\'t a valid word'
    elsif valid_word
      'Sorry, this isn\'t an enlish word'
    else
      'Sorry. Try again'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/new.html.erb
<div class="container">
<h1>Current score is <%= session[:score] %></h1>
<div class="reset-wrapper">
  <%= link_to 'Reset Score', reset_path, method: :post, class: 'btn-reset' %>
</div>
  <div class="letter-wrapper">
    <% @letters.each do |letter| %>
      <div class="letter"><%= letter %></div>
    <% end %> 
  </div>
  <div class="form-wrapper">
      <form action="/score" method="post">
      <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
      <%= hidden_field_tag :letters, @letters %>
      <%= hidden_field_tag :start, @start %>
      <div class="input-wrapper">
        <input type="text" name="word" placeholder="Type your word">
        <input type="submit" value="Submit">
      </div>
    </form>
  </div>
</div>

app/views/games/score.html.erb
<div class="container container-score">
  <h1 class="score"><%= session[:score] %></h1>
  <h3><%= @message %></h3>
  <%= link_to 'Play again', new_path, class: 'btn-reset' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>